# SPDX-License-Identifier: Apache-2.0
"""Clean one-command/resume acceptance for existing-report follow-up."""
import hashlib,json,pathlib,subprocess,tempfile,os
from .test_one_command_v63 import make
P=pathlib.Path;HERE=P(__file__).resolve().parent;REPO=HERE.parents[1]
def canon(x):return json.dumps(x,sort_keys=True,separators=(',',':')).encode()
def main():
 with tempfile.TemporaryDirectory() as td:
  root=P(td);source=make(root);path=root/'profile.json';p=json.loads(path.read_text());p['schema_version']='6.7';p['reporter_context']='INTERNAL_EMPLOYEE';p['submission_channel']='ARM_INTERNAL_PSIRT';p['contract_release'].update({'version':'6.7.0','severity_contract':'AUTO_DISCOVER','policy_contract':'AUTO_DISCOVER','policy_schema_extension':'AUTO_DISCOVER','reporting_contract':'AUTO_DISCOVER','followup_contract':'AUTO_DISCOVER'})
  threat=next(x for x in p['automation']['stages'] if x['phase']=='THREAT_POLICY_COLLECTION');threat['required_outputs'].append('policy-reconciliation-input.json');seal=next(x for x in p['automation']['stages'] if x['phase']=='PACKAGE_AND_SEAL')
  stages=[{'stage_id':'policy-reconciliation','phase':'POLICY_RECONCILIATION','depends_on':['integrate','reproduce','collect-current-tickets','collect-threat-policy'],'builtin':'POLICY_PRECEDENCE_RECONCILIATION','required_outputs':['POLICY-INDEX.json','POC-EVIDENCE-INDEX.json','NOVELTY-INDEX.json','POLICY-VALIDATION.json']},{'stage_id':'severity-calibration','phase':'SEVERITY_CALIBRATION','depends_on':['integrate','reproduce'],'builtin':'TECHNICAL_SEVERITY_CALIBRATION','required_outputs':['SEVERITY-INDEX.json','SEVERITY-VALIDATION.json']},{'stage_id':'existing-report-followup','phase':'EXISTING_REPORT_FOLLOWUP','depends_on':['integrate','reproduce','policy-reconciliation','severity-calibration','collect-historical-tickets','collect-current-tickets'],'builtin':'EXISTING_REPORT_FOLLOWUP_ASSESSMENT','required_outputs':['EXISTING-REPORT-FOLLOWUP-INDEX.json','EXISTING-REPORT-FOLLOWUP-INDEX.md','FOLLOWUP-VALIDATION.json']},{'stage_id':'package-export','phase':'PACKAGE_EXPORT','depends_on':['integrate','reproduce','policy-reconciliation','severity-calibration','existing-report-followup'],'builtin':'INTERNAL_TECHNICAL_PACKAGE_EXPORT','required_outputs':['INDEX.json','INDEX.md','VALIDATION-RECEIPT.json']},{'stage_id':'population-report','phase':'POPULATION_SCOPED_REPORTING','depends_on':['integrate','policy-reconciliation','package-export'],'builtin':'POPULATION_SCOPED_SUMMARY','required_outputs':['POPULATION-SCOPED-REPORT.json','POPULATION-SCOPED-REPORT.md']}]
  i=p['automation']['stages'].index(seal);p['automation']['stages'][i:i]=stages;seal['depends_on']+=['policy-reconciliation','severity-calibration','existing-report-followup','package-export','population-report'];path.write_bytes(canon(p)+b'\n')
  ledger=root/'calls.json';env={**os.environ,'V63_CALL_LEDGER':str(ledger),'V63_INTERRUPT_STAGE':'reproduce'};cmd=['uv','run','--no-sync','metis','--firmware-campaign',str(path),'--codebase-path',str(source),'--resume'];first=subprocess.run(cmd,cwd=REPO,env=env,capture_output=True,text=True);env.pop('V63_INTERRUPT_STAGE');second=subprocess.run(cmd,cwd=REPO,env=env,capture_output=True,text=True);before=ledger.read_bytes();third=subprocess.run(cmd,cwd=REPO,env=env,capture_output=True,text=True);index=list((root/'automation/stages/existing-report-followup').glob('*/EXISTING-REPORT-FOLLOWUP-INDEX.json'));calls=json.loads(ledger.read_text())
  body=json.loads(index[0].read_text()) if len(index)==1 else {};ok=first.returncode!=0 and second.returncode==third.returncode==0 and before==ledger.read_bytes() and body.get('root_count')==0 and calls.get('provider_calls')==1 and 'adapter:existing-report-followup' not in calls
  result={'format_version':'firmware-capability-v6.7-one-command-acceptance','result':'PASS' if ok else 'FAIL','resume_passed':second.returncode==0,'stable_resume':third.returncode==0 and before==ledger.read_bytes(),'provider_completed_calls_repeated':0 if calls.get('provider_calls')==1 else None,'followup_builtin_used':'adapter:existing-report-followup' not in calls,'errors':[] if ok else [first.stderr[-400:],second.stderr[-1500:],third.stderr[-500:]]};result['content_hash']=hashlib.sha256(canon(result)).hexdigest();print(json.dumps(result,sort_keys=True));return not ok
if __name__=='__main__':raise SystemExit(main())
