# SPDX-License-Identifier: Apache-2.0
"""Clean one-command and five fail-point/resume acceptance for capability 6.3."""
import hashlib,json,os,pathlib,subprocess,sys,tempfile
P=pathlib.Path;HERE=P(__file__).resolve().parent;REPO=HERE.parents[1]
PH=[('collect-source','SOURCE_COLLECTION'),('collect-historical-tickets','HISTORICAL_TICKET_COLLECTION'),('collect-current-tickets','CURRENT_TICKET_COLLECTION'),('collect-threat-policy','THREAT_POLICY_COLLECTION'),('build-candidate','CANDIDATE_BUILD'),('metis-health','METIS_HEALTH'),('metis-one','METIS_CALIBRATION_1'),('metis-twenty','METIS_CALIBRATION_20'),('metis-full','METIS_FULL_SCAN'),('metis-capacity','METIS_CALIBRATION_100'),('validate-packets','PACKET_VALIDATION'),('integrate','AUTHORITATIVE_INTEGRATION'),('reproduce','REPRODUCTION'),('package-seal','PACKAGE_AND_SEAL')]
OUT={'collect-source':['source-manifest.json','active-source-membership.json','indirect-call-inventory.json','documentation-manifest.json','component-registry.json'],'collect-historical-tickets':['historical-ticket-manifest.json','ticket-source-relations.json','connector-receipts.json'],'collect-current-tickets':['current-ticket-manifest.json','ticket-source-relations.json','connector-receipts.json'],'collect-threat-policy':['threat-policy-manifest.json','connector-receipts.json','security-properties.json','programme-rules.json','advisory-fix-regression.json','programme-threat-comparison.json'],'build-candidate':['candidate-build.json','contract-discovery.json','exact-build-bindings.json','knowledge-fts.json','independent-rebuild.json'],'metis-health':['provider-health.json'],'metis-one':['calibration.json'],'metis-twenty':['calibration.json'],'metis-full':['incremental-finalization.json','rendered-prompt-receipts.json','coverage-schedules.json','context-cache-receipts.json'],'metis-capacity':['capacity-decision.json'],'validate-packets':['stage.json','terminal-decision-capsules.json','review-bindings.json','fp-no-bug-audits.json','classification-reopen-proposals.json','terminal-change-anomaly-gate.json'],'integrate':['integration.packet.json','root-fingerprints.json','fts-index-receipt.json','root-property-mappings.json','variant-searches.json','scope-invalidation.json'],'reproduce':['reproduction-frontier.json','backend-capabilities.json','rerun-manifests.json','reproducer-reuse.json','candidate-patch-state.json','control-triplets.json'],'package-seal':['candidate-a.db','candidate-b.db','candidate-a.dump','candidate-b.dump','report-a.md','report-b.md','delivery-a.json','delivery-b.json','packages-a/manifest.json','packages-b/manifest.json','validation-gates.json','current-frontier.json','final-receipts.json']}
def canon(x):return json.dumps(x,sort_keys=True,separators=(',',':')).encode()
def make(root):
 source=root/'source';source.mkdir();(source/'source.c').write_text('int main(void){return 0;}\n');tree=hashlib.sha256(canon([{'path':'source.c','sha256':hashlib.sha256((source/'source.c').read_bytes()).hexdigest()}])).hexdigest();adapter=str(HERE/'v63_acceptance_fixture.py');st=[]
 for i,(sid,ph) in enumerate(PH):
  z={'stage_id':sid,'phase':ph,'depends_on':[] if i==0 else [PH[i-1][0]],'adapter':[sys.executable,adapter,'--stage',sid,'--context','{context}'],'required_outputs':OUT[sid]}
  if ph=='PACKET_VALIDATION':z['worker_adapter']=[sys.executable,adapter,'--stage','validate-worker','--context','{context}']
  if ph=='AUTHORITATIVE_INTEGRATION':z['idempotent_noop_allowed']=True
  if ph=='REPRODUCTION':z['continue_on_blocked_dependencies']=True
  if ph=='PACKAGE_AND_SEAL':z['continue_on_blocked_dependencies']=True;z['deterministic_pairs']=[['candidate-a.db','candidate-b.db'],['candidate-a.dump','candidate-b.dump'],['report-a.md','report-b.md'],['delivery-a.json','delivery-b.json'],['packages-a/manifest.json','packages-b/manifest.json']]
  st.append(z)
 profile={'schema_version':'6.3','contract_release':{'version':'6.3.0','manifest':'AUTO_DISCOVER','core_database_contract':'AUTO_DISCOVER','capability_schema':'AUTO_DISCOVER','accuracy_contract':'AUTO_DISCOVER','accuracy_schema_extension':'AUTO_DISCOVER','knowledge_contract':'AUTO_DISCOVER','knowledge_schema_extension':'AUTO_DISCOVER','automatic':True},'project':{'project_id':'fixture','components':[{'component_id':'core','repository':'https://example.invalid/core.git','revision':'a'*40,'tree_sha256':tree,'source_checkout_required':True}]},'governance':{'candidate_database_only':True,'production_write_target_configured':False,'production_write_attempts':0},'automation':{'format_version':'firmware-autonomous-campaign-v1','campaign_reader_limit':11,'provider_worker_configuration_limit':100,'connectors':[{'kind':k,'read_only':True} for k in ('TICKET','JIRA','INTIGRITI','CONFLUENCE')],'metis_cli':{'primary_component_id':'core','candidate':'candidate/fixture.db','state':'automation'},'stages':st}};(root/'profile.json').write_bytes(canon(profile)+b'\n');return source
def main():
 results=[]
 with tempfile.TemporaryDirectory() as td:
  for fail in ('collect-source','metis-one','validate-worker','reproduce','package-seal'):
   root=P(td)/fail;root.mkdir();source=make(root);ledger=root/'calls.json';env={**os.environ,'V63_CALL_LEDGER':str(ledger),'V63_INTERRUPT_STAGE':fail};cmd=['uv','run','--no-sync','metis','--firmware-campaign',str(root/'profile.json'),'--codebase-path',str(source),'--resume'];first=subprocess.run(cmd,cwd=REPO,env=env,capture_output=True,text=True);env.pop('V63_INTERRUPT_STAGE');second=subprocess.run(cmd,cwd=REPO,env=env,capture_output=True,text=True);before=ledger.read_bytes() if ledger.exists() else b'';third=subprocess.run(cmd,cwd=REPO,env=env,capture_output=True,text=True);calls=json.loads(ledger.read_text()) if ledger.exists() else {};logs=list((root/'automation/failed-stages').glob('**/stderr.log'));detail=logs[-1].read_text()[-1500:] if logs else second.stderr[-1000:];results.append({'stage':fail,'interrupted':first.returncode!=0,'resumed':second.returncode==0,'stable_resume':third.returncode==0 and before==ledger.read_bytes() if ledger.exists() else False,'provider_calls':calls.get('provider_calls',0),'second_error':detail})
 ok=all(x['interrupted'] and x['resumed'] and x['stable_resume'] and x['provider_calls']<=1 for x in results);print(json.dumps({'result':'PASS' if ok else 'FAIL','one_command':'uv run --no-sync metis --firmware-campaign <profile.json> --codebase-path <source> --resume','provider_completed_calls_repeated':0 if ok else None,'results':results},sort_keys=True));return not ok
if __name__=='__main__':raise SystemExit(main())
