# SPDX-License-Identifier: Apache-2.0
"""Clean one-command interruption/resume acceptance for severity calibration."""
import hashlib,json,pathlib,subprocess,tempfile,os
from .test_one_command_v63 import make
P=pathlib.Path;HERE=P(__file__).resolve().parent;REPO=HERE.parents[1]
def canon(x):return json.dumps(x,sort_keys=True,separators=(',',':')).encode()
def main():
 with tempfile.TemporaryDirectory() as td:
  root=P(td);source=make(root);path=root/'profile.json';profile=json.loads(path.read_text());profile['schema_version']='6.5';profile['contract_release'].update({'version':'6.5.0','severity_contract':'AUTO_DISCOVER'})
  seal=next(x for x in profile['automation']['stages'] if x['phase']=='PACKAGE_AND_SEAL');seal['depends_on'].append('package-export');profile['automation']['stages'].insert(-1,{'stage_id':'severity-calibration','phase':'SEVERITY_CALIBRATION','depends_on':['integrate','reproduce'],'builtin':'TECHNICAL_SEVERITY_CALIBRATION','required_outputs':['SEVERITY-INDEX.json','SEVERITY-VALIDATION.json']});profile['automation']['stages'].insert(-1,{'stage_id':'package-export','phase':'PACKAGE_EXPORT','depends_on':['integrate','reproduce','severity-calibration'],'builtin':'INTERNAL_TECHNICAL_PACKAGE_EXPORT','required_outputs':['INDEX.json','INDEX.md','VALIDATION-RECEIPT.json']});path.write_bytes(canon(profile)+b'\n')
  ledger=root/'calls.json';env={**os.environ,'V63_CALL_LEDGER':str(ledger),'V63_INTERRUPT_STAGE':'reproduce'};cmd=['uv','run','--no-sync','metis','--firmware-campaign',str(path),'--codebase-path',str(source),'--resume'];first=subprocess.run(cmd,cwd=REPO,env=env,capture_output=True,text=True);env.pop('V63_INTERRUPT_STAGE');second=subprocess.run(cmd,cwd=REPO,env=env,capture_output=True,text=True);calls_before=ledger.read_bytes();third=subprocess.run(cmd,cwd=REPO,env=env,capture_output=True,text=True);calls=json.loads(ledger.read_text());s=list((root/'automation/stages/severity-calibration').glob('*/SEVERITY-INDEX.json'));p=list((root/'automation/stages/package-export').glob('*/INDEX.json'))
  ok=first.returncode!=0 and second.returncode==third.returncode==0 and calls_before==ledger.read_bytes() and len(s)==len(p)==1 and json.loads(s[0].read_text()).get('valid_root_count')==0 and json.loads(p[0].read_text()).get('format_version')=='firmware-internal-package-export-v6.5' and calls.get('provider_calls')==1 and 'adapter:severity-calibration' not in calls
  result={'format_version':'firmware-capability-v6.5-one-command-acceptance','result':'PASS' if ok else 'FAIL','resume_passed':second.returncode==0,'stable_resume':third.returncode==0 and calls_before==ledger.read_bytes(),'provider_completed_calls_repeated':0 if calls.get('provider_calls')==1 else None,'severity_builtin_used':'adapter:severity-calibration' not in calls,'errors':[] if ok else [first.stderr[-500:],second.stderr[-1200:],third.stderr[-500:]]};result['content_hash']=hashlib.sha256(canon(result)).hexdigest();print(json.dumps(result,sort_keys=True));return not ok
if __name__=='__main__':raise SystemExit(main())
